# Generated by Django 4.2 on 2024-04-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='preco',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
